services:
  app_abm_users:
    build:
      context: .
      dockerfile: tp.integrador/Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8081"
    environment:
        - DB_URL
        - DB_USERNAME
        - DB_PASSWORD
    restart: always
    depends_on:
      abm_user:
        condition: service_healthy
  abm_user:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 10