services:
  app_abm_users:
    build:
      context: .
      dockerfile: tp.integrador/Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8081"
    environment:
      #DB_URL: jdbc:mysql://abm_user:3306/tp_up_devops?createDatabaseIfNotExist=true&serverTimezone=UTC
      #DB_USERNAME: developer
      #DB_PASSWORD: 1234
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      abm_user:
        condition: service_healthy
  abm_user:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      #MYSQL_ROOT_PASSWORD: 1234
      #MYSQL_PASSWORD: 1234
      #MYSQL_USER: developer
      #MYSQL_DATABASE: tp_up_devops
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
