services:
  app_abm_users:
    build:
      context: .
      dockerfile: tp.integrador/Dockerfile
    mem_limit: 512m
    ports:
      - "8080:8081"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on:
      abm_user:
        condition: service_healthy
  abm_user:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    build:
      args:
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
