INSERT INTO PRODUCT(DESCRIPTION,AMOUNT)VALUES('Cafetera',50.0);
INSERT INTO PRODUCT(DESCRIPTION,AMOUNT)VALUES('Horno',250.0);
INSERT INTO PRODUCT(DESCRIPTION,AMOUNT)VALUES('Smart TV Samsung',30000.0);
INSERT INTO PRODUCT(DESCRIPTION,AMOUNT)VALUES('Teclado retroilumniado',30.0);
INSERT INTO PRODUCT(DESCRIPTION,AMOUNT)VALUES('Monitor LG',70.0);


INSERT INTO USERS( EMAIL, PASSWORD, ROLE)VALUES('test@test.com', 'asd', 'admin');