INSERT INTO PRODUCT(ID_PRODUCT,DESCRIPTION,AMOUNT)VALUES(1,'Cafetera',50.0);
INSERT INTO PRODUCT(ID_PRODUCT,DESCRIPTION,AMOUNT)VALUES(2,'Horno',250.0);
INSERT INTO PRODUCT(ID_PRODUCT,DESCRIPTION,AMOUNT)VALUES(3,'Smart TV Samsung',30000.0);
INSERT INTO PRODUCT(ID_PRODUCT,DESCRIPTION,AMOUNT)VALUES(4,'Teclado retroilumniado',30.0);
INSERT INTO PRODUCT(ID_PRODUCT,DESCRIPTION,AMOUNT)VALUES(5,'Monitor LG',70.0);


INSERT INTO USERS(ID_USER, EMAIL, PASSWORD, ROLE)VALUES(1,'test@test.com', 'asd', 'admin');