DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ORDERS;

create table PRODUCT(
    ID_PRODUCT  INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPTION CHARACTER VARYING(255),
    AMOUNT      NUMERIC not null
);
create table USERS(
    ID_USER INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL CHARACTER VARYING(50) NOT NULL,
    PASSWORD CHARACTER VARYING(50) NOT NULL,
    ROLE CHARACTER VARYING(20)
);

CREATE SEQUENCE ORDERS_SEQ START WITH 1 INCREMENT BY 1;
create table ORDERS(
    ID_ORDER INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_USER INTEGER,
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (ID_USER)
    REFERENCES USERS(ID_USER)
);

CREATE SEQUENCE ORDER_PRODUCTS_SEQ START WITH 1 INCREMENT BY 1;
create table ORDER_PRODUCTS(
    ID_ORDER_PRODUCT INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_ORDER INTEGER,
    ID_PRODUCT INTEGER,
    CONSTRAINT FK_ORDERPRODUCT_ORDER FOREIGN KEY (ID_ORDER)
    REFERENCES ORDERS(ID_ORDER),
    CONSTRAINT FK_ORDERPRODUCT_PRODUCT FOREIGN KEY (ID_PRODUCT)
    REFERENCES PRODUCT(ID_PRODUCT)
);

