name: cicd build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: build with Maven
      run: mvn clean install
      working-directory: ./tp.integrador
      
    - name: Define version
      id: vars
      run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV
      
    #- name: Build & push Docker image
    #  uses: mr-smithers-excellent/docker-build-push@v6
    #  with:
    #    image: rodrigos21/devops-github-actions
    #    tags: ${{ env.VERSION }},latest
    #    registry: docker.io
    #    dockerfile: tp.integrador/Dockerfile
    #    context: tp.integrador
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
        #buildArgs: | 
        #build-args: |
         #   DB_URL=${{ secrets.DB_URL }}
         #   DB_USERNAME=${{ secrets.DB_USERNAME }}
         #   DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      #env:
      #    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      #    MYSQL_USER: ${{ secrets.MYSQL_USER }}
      #    MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}

      # Paso 2: Ejecutar Docker Compose con las variables de entorno necesarias
    #- name: Run Docker Compose
    #  run: docker compose up --build -d
    #  env:
          # variables

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        registry: docker.io
        dockerfile: tp.integrador/Dockerfile
        context: tp.integrador
        push: true
        tags:  ${{ env.VERSION }},latest
        build-args: |
          DB_URL=${{ secrets.DB_URL }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}